image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - deploy

variables:
  PROJECT_NAME: UITManagerAgent
  PROJECT_NAME_TEST: UITManagerAgent.Tests
  BUILD_CONFIGURATION: Debug

build:
  stage: build
  script:
    - dotnet restore $CI_PROJECT_DIR/Code/$PROJECT_NAME/$PROJECT_NAME.sln  
    - dotnet build --no-restore $CI_PROJECT_DIR/Code/$PROJECT_NAME/$PROJECT_NAME.sln -c $BUILD_CONFIGURATION
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/Code/$PROJECT_NAME/bin/$BUILD_CONFIGURATION"
      - "$CI_PROJECT_DIR/Code/$PROJECT_NAME_TEST/bin/$BUILD_CONFIGURATION"
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  stage: test
  script:
    - dotnet test --no-build "$CI_PROJECT_DIR/Code/$PROJECT_NAME/$PROJECT_NAME.sln" -c $BUILD_CONFIGURATION
  dependencies:
    - build
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/Code/$PROJECT_NAME/bin/$BUILD_CONFIGURATION/*.trx"  
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

deploy:
  stage: deploy
  script:
    - echo "Déploiement des artefacts depuis ./Code/$PROJECT_NAME/bin/$BUILD_CONFIGURATION pour l'environnement de développement"
  artifacts:
    paths:
      - "./Code/$PROJECT_NAME/bin/$BUILD_CONFIGURATION"
    expire_in: 1 week
  dependencies:
    - build
    - test
  environment:
    name: development
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
