.windows_job:
  tags:
    - saas-windows-medium-amd64
  before_script:
    - Set-Variable -Name "time" -Value (Get-Date -Format "HH:mm")
    - Write-Host "started by $env:GITLAB_USER_NAME / @$env:GITLAB_USER_LOGIN"

variables:
  PROJECT_NAME: UITManagerAgent
  PROJECT_NAME_TEST: UITManagerAgent.Tests
  BUILD_CONFIGURATION: Debug

build:
  extends: .windows_job
  stage: build
  script:
    - dotnet restore "$env:CI_PROJECT_DIR\\Code\\$env:PROJECT_NAME\\$env:PROJECT_NAME.sln"
    - dotnet build --no-restore "$env:CI_PROJECT_DIR\\Code\\$env:PROJECT_NAME\\$env:PROJECT_NAME.sln" -c $env:BUILD_CONFIGURATION
  artifacts:
    paths:
      - "Code/UITManagerAgent/bin/Debug"
      - "Code/UITManagerAgent.Tests/bin/Debug"
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_PIPELINE_SOURCE == "web"'

test:
  extends: .windows_job
  stage: test
  script:
    - dotnet --version
    - dotnet test --no-build "Code\\UITManagerAgent\\UITManagerAgent.sln" -c Debug
  dependencies:
    - build
  artifacts:
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_PIPELINE_SOURCE == "web"'

deploy:
  extends: .windows_job
  stage: deploy
  script:
    - echo "Déploiement des artefacts depuis ./Code/$env:PROJECT_NAME/bin/$env:BUILD_CONFIGURATION pour l'environnement de développement"
  artifacts:
    paths:
      - "Code/UITManagerAgent/bin/Debug"
    expire_in: 1 week
  dependencies:
    - build
    - test
  environment:
    name: development
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_PIPELINE_SOURCE == "web"'
