# .NET CI/CD Pipeline pour GitLab - Environnement de Développement

image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - deploy

variables:
  PROJECT_NAME: UITManagerAgent
  BUILD_CONFIGURATION: Debug

build:
  stage: build
  script:
    - dotnet restore ./Code/$PROJECT_NAME.sln
    - dotnet build --no-restore ./Code/$PROJECT_NAME.sln -c $BUILD_CONFIGURATION
  artifacts:
    paths:
      - "./Code/$PROJECT_NAME/bin/$BUILD_CONFIGURATION"
    expire_in: 1 week

# Job de test
test:
  stage: test
  script:
    - dotnet test --no-build ./Code/$PROJECT_NAME.sln -c $BUILD_CONFIGURATION --logger "trx;LogFileName=${PROJECT_NAME}_test_results.trx"
  artifacts:
    when: always
    paths:
      - "./Code/$PROJECT_NAME/bin/$BUILD_CONFIGURATION/*.trx"
    expire_in: 1 week
  dependencies:
    - build

deploy:
  stage: deploy
  script:
    - echo "Déploiement des artefacts depuis ./Code/$PROJECT_NAME/bin/$BUILD_CONFIGURATION pour l'environnement de développement"
  artifacts:
    paths:
      - "./Code/$PROJECT_NAME/bin/$BUILD_CONFIGURATION"
    expire_in: 1 week
  dependencies:
    - build
    - test
  environment:
    name: development
