.windows_job:
  tags:
    - saas-windows-medium-amd64
  before_script:
    - Set-Variable -Name "time" -Value (Get-Date -Format "HH:mm")
    - Write-Host "started by $env:GITLAB_USER_NAME / @$env:GITLAB_USER_LOGIN"

variables:
  PROJECT_NAME: UITManagerAgent
  PROJECT_NAME_TEST: UITManagerAgent.Tests
  BUILD_CONFIGURATION: Debug
  DOC_OUTPUT: "$env:CI_PROJECT_DIR\\Code\\docs"
  DOC_XML_PATH: "$env:CI_PROJECT_DIR\\Code\\$env:PROJECT_NAME\\bin\\$env:BUILD_CONFIGURATION\\net8.0\\Documentation.xml"

build:
  extends: .windows_job
  stage: build
  script:
    - dotnet restore "$env:CI_PROJECT_DIR\\Code\\$env:PROJECT_NAME\\$env:PROJECT_NAME.sln"
    - dotnet build --no-restore "$env:CI_PROJECT_DIR\\Code\\$env:PROJECT_NAME\\$env:PROJECT_NAME.sln" -c $env:BUILD_CONFIGURATION
  artifacts:
    paths:
      - "$CI_PROJECT_DIR\\Code\\$env:PROJECT_NAME\\bin\\$env:BUILD_CONFIGURATION"
      - "$CI_PROJECT_DIR\\Code\\$env:PROJECT_NAME_TEST\\bin\\$env:BUILD_CONFIGURATION"
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  extends: .windows_job
  stage: test
  script:
    - dotnet --version
    - dotnet test --no-build "$env:CI_PROJECT_DIR\\Code\\$env:PROJECT_NAME\\$env:PROJECT_NAME.sln" -c $env:BUILD_CONFIGURATION
  dependencies:
    - build
  artifacts:
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

deploy:
  extends: .windows_job
  stage: deploy
  script:
    - echo "Déploiement des artefacts depuis ./Code/$env:PROJECT_NAME/bin/$env:BUILD_CONFIGURATION pour l'environnement de développement"
  artifacts:
    paths:
      - "./Code/$env:PROJECT_NAME/bin/$env:BUILD_CONFIGURATION"
    expire_in: 1 week
  dependencies:
    - build
    - test
  environment:
    name: development
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
